### ISSUE TITLE
Logging interval setting issue

### ISSUE THREAD

**Issue by ghost** [Sensirion/SmartGadget-iOS#1]
Hello,

Using iOS _MyAmbience_ application (`v1.4.0`), going through the SmartGadget settings' menu to set the logging interval does not properly work.

For example, if we set it to 1 minute, let the device run 2 or 3 minutes, export the data, then the measurements are on a 1 minute basis, perfect.
But if you export the data again, the new measurements are back on a 1 second basis.

For example, below is the exported data when I set the interval to 1 minute.
First, by default, it is set to 1 second.
Then we clearly see the 1 minute basis.
And then it's back to 1 second basis, as per the second export.

```
1597499034.566	28.990
1597499035.562	29.020
1597499036.565	29.020
1597499037.572	28.990
1597499038.556	29.010
1597499100.000	28.980
1597499160.000	29.020
1597499220.000	29.020
1597499220.028	29.040
1597499221.025	29.040
1597499222.022	29.020
1597499223.021	29.040
1597499224.018	29.040
```

It's as if reaching the SmartGadget settings' menu performed a reset of the logging interval...

Could it be possible to have a look at this please ?

Thank you very much 👍

**Comment by MBjoern** [comment]
Hi

Thank you for your comments.

Long story short: Indeed, this is a confusing, it's subject to change but originally intended.

I hope I followed your description correctly, let's look at your log and see how this happened. 

The app, when running and connected to the Gadget, is receiving live data from the Smart Gadget in a 1 second interval. This is fixed and can not be changed, but only happens, while being connected to the Gadget.

The logging interval feature sets the interval in which the sensor measurement is cached on the Smart Gadget for later download. 

Both of these are combined in the App's storage, e.g. if you connect to your smart gadget, then you receive live values in 1 second interval. If you download the data from the gadget, the data of that time range will have the logging interval set (in your example: 1min). If you stay connected with the gadget, the live values with 1 second interval will keep coming in for all the time after the "sync"/download.

Connected with Gadget -> interval is 1 second:
1597499034.566	28.990
1597499035.562	29.020
1597499036.565	29.020
1597499037.572	28.990
1597499038.556	29.010

Downloaded from gadget -> interval is 1 minute, as adjustable in the gadget settings
1597499100.000	28.980
1597499160.000	29.020
1597499220.000	29.020

Connected with Gadget -> interval is 1 second:
1597499220.028	29.040
1597499221.025	29.040
1597499222.022	29.020
1597499223.021	29.040
1597499224.018	29.040

What you export, is what you have in your app and see on the screen, a mix of live values and values downloaded from the gadget. 
Does this explain the issue described?

As I've mentioned, this feature is subject to change. We have some ideas how to improve this in a future version of MyAmbience, as it is indeed quite confusing. If you have any suggestions, don't hesitate to share.

**Comment by sensusr** [comment]
Hi @MBjoern, and thank you very much for your detailed explanation.
I'm able to reproduce the behaviour you just explained ; the internal device logging interval is and remains the user-defined one.
But while connected, MyAmbience receives data on a 1 second basis, adding it to the data exported from the device.
That's clear :)
Perhaps you should use "live data" for real-time counters display only, and not add it to the exported data.

**Comment by ghost** [comment]
Hi @MBjoern, and thank you very much for your detailed explanation.
I'm able to reproduce the behaviour you just explained ; the internal device logging interval is and remains the user-defined one.
But while connected, MyAmbience receives data on a 1 second basis, adding it to the data exported from the device.
That's clear :)

As an enhancement, perhaps you should use "live data" (1 second basis) for real-time counters display only, and not add it to the exported data (as it then "breaks" the user-defined interval).

Anyway, thank you very much for your great support 👍

**Comment by MBjoern** [comment]
Hi @sensusr , I'm glad that it got clear now. 
Agreed, that would be a great enhancement.

Stay tuned for future updates of the app. We'll be glad to hear your comments and feedback on the adaption of the feature.
Best regards
